<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.qoop</groupId>
        <artifactId>qoop-container</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>sms-integration-container</artifactId>

    <properties>
        <sms-integration.version>0.0.1-SNAPSHOT</sms-integration.version>
        <sms-integration-shared-core.version>0.0.1-SNAPSHOT</sms-integration-shared-core.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>sms-integration-infrastructure</artifactId>
            <version>${sms-integration.version}</version>
        </dependency>

        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>sms-integration-presentation</artifactId>
            <version>${sms-integration.version}</version>
        </dependency>

        <!--        Test        -->
        <dependency>
            <groupId>io.qoop</groupId>
            <artifactId>sms-integration-shared-core</artifactId>
            <version>${sms-integration-shared-core.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
